name: demo
on:
  push:
    branches: [main]
  pull_request:
    types: [opened,reopened,synchronize]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Today is $(date +%Y-%h-%d)"
