name: hello world
on:
  push:
    branches:
      - 'main'
      - 'release/**'
      - '!dev/**'
    paths:
      - '!README.md'
      - '!docs/**'
      - '**.js'
  pull_request:
    type: [opened,reopened,synchronize]
    branches:
      - 'main'
      - 'release/**'
      - '!dev/**'
    paths:
      - '!README.md'
      - '!docs/**'
      - '**.js'
  workflow_dispatch:
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODAY=$(date +%y-%m-%d)" >> $GITHUB_ENV
      - run: echo Hello world, today is $TODAY
