name: secrets
on:
  push:
    branches: [main]
  pull_request:
    type: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  fetch-secrets:
    - uses: actions/checkout@v2
    - run: echo This is my secrets "${{secrets.MY_SECRET}}"
    - run: ./cli.js rdstr 24
